### Basic Application Settings

### Server Settings
server:
  port: 8282

### Application Settings
application:
  client:
    endpoint:
      consulta-cpf: "https://user-info.herokuapp.com/users/"
  kafka:
    server: "18.231.179.30:9092"
